### ISSUE TITLE
Encountering some issues while using Fast Olympic Coding

### ISSUE THREAD

**Issue by Kolandaina** [sam20908/vscode-fastolympiccoding#4] opened 2024-07-24 05:53 UTC
I tried using Fast Olympic Coding, but when I ran the test case downloaded from Competitive Companion Web, I found that it reported these errors. What is the reason for this? Can you help me solve it
`cc1plus.exe: fatal error: code\C\code\test\2.cpp: No such file or directory
compilation terminated.`
![e28b19d603dcd71efa94012ed1b5442](https://github.com/user-attachments/assets/cda0657a-dd42-4095-a897-c40c73d586b4)

**Comment by yuyuzks** [comment] 2024-07-24 05:56
@sam20908

**Comment by sam20908** [comment] 2024-07-24 08:13
@yuyuzks Hello, you probably need to create the directory `C\code\test` (I assume the `code` prefix is some nonsense). I do wonder how the code prefix got in there. I will need to check.

**Comment by sam20908** [comment] 2024-07-24 08:14
If you still have issues, please post your run settings for your cpp

**Comment by yuyuzks** [comment] 2024-07-24 08:35
@sam20908 The problem has been resolved, thank you

**Comment by yuyuzks** [comment] 2024-07-24 09:08
@sam20908 
But I found another problem while using it, that is, when I use "Ctrl+Alt+I", there is no response, no file directory appears, and I cannot insert file templates. I am sure that my shortcut key "Ctrl+Alt+I" does not conflict with other operations, because "Ctrl+Alt+I" only binds to fastolympiccoding. insertFileTemplate.
Additionally, have you considered displaying both the correct answer downloaded by Competitive Companion Web and my incorrect output when a 'WA' (Wrong Answer) occurs? This would make it easier for us to see the discrepancy between my answer and the correct one, allowing us to modify the code more conveniently to pass the test.

**Comment by sam20908** [comment] 2024-07-24 09:19
@yuyuzks I believe you need to go to settings and look for the settings inside the image

![image](https://github.com/user-attachments/assets/fc8c5854-5c37-4a94-b99d-6f8a7ae8f1ea)

I will add this image to README soon

**Comment by sam20908** [comment] 2024-07-24 17:05
If the issue is solved, I will close it after your confirmation

**Comment by sam20908** [comment] 2024-07-24 17:13
> Additionally, have you considered displaying both the correct answer downloaded by Competitive Companion Web and my incorrect output when a 'WA' (Wrong Answer) occurs? This would make it easier for us to see the discrepancy between my answer and the correct one, allowing us to modify the code more conveniently to pass the test.

I actually didn't before because my design choices, but I plan to show that with the option to view it with VSCode's built-in diff editor (if that's even possible)

**Comment by sam20908** [comment] 2024-07-24 22:33
closed by 232e7b0cee568f7a73cef9645c52b6d6e215954f which is in version 0.3.1 which I pushed. Feel free to reopen if you have any additional comments

**Comment by sam20908** [comment] 2024-07-24 22:34
Example:

![image](https://github.com/user-attachments/assets/b0c78f1e-0fb7-4ab3-a07e-bea053f342c4)

**Closed by sam20908** 2024-07-24 22:33 UTC
